### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by gorterd** [tasnim-s/HoloCron#1]
Fantastic work on your design docs, Tasnim! I opened a different issue for each design doc; overall, I don't have too much for you to revise, mostly design choices that could go either way.  Feel free to drop questions about any of my feedback as a comment, or Slack me! Big apologies for the slowness of my feedback, but do let me know if you have questions or need anything else.

### To Revise:
  - [x] `Profiles`: I'd recommend holding off on the friends list until you implement the `Friends` MVP
  - `Friending`: 
    - [x] Can you elaborate a bit on how this will work: are you going to implement a search feature, or will there be a more basic users index page? If the second, are you going to model it after the look and feel of the search page or some other page on Facebook?
    - [x] Do you intend to replicate the process of sending / accepting friend `requests`? While this would make this a pretty sizable MVP, I think you could definitely do it. It's up to you though (and is an idea for a bonus feature)
    - `News Feed`:
      - [x] I noticed you mentioned liking posts in your `News Feed` MVP; I'd leave this until your start your dedicated Likes bonus MVP
      - How is a user's news feed customizable? How will you sort the posts?
### Suggestions / Thoughts:
  - `Comments` Do you intend to implement nested comments (comments on comments)?
  - `News Feed` I noticed this is your first mention of likes / reactions. I think that's fine to leave until this MVP (since the others already are pretty involved). 
  - `Likes` Since this is a smaller MVP, I'd recommend you consider replicating all the reactions (not just liking), but it's up to you. Also, remember to include the ability to unlike

**Comment by tasnim-s** [comment]
1. Removed friends list from Profile MVP
2. Find Friends page (users index) will be implemented to look for other users.
3. Clicking Add Friend will send invite to the Find Friends page of the requested user to accept before adding that connection to friends table
4. Likes will now contain reactions as well to give more options to users.
