### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by gorterd** [tasnim-s/HoloCron#2]
- [x] `users`: You'll need to add more fields to your `users` table, to cover all the data that can be added to a user's profile (e.g. bio/description, location, etc)
  - [ ] Be sure to add has_many associations to all your tables
  - [ ] Since likes can given to both posts and comments, I'd recommend using a polymorphic association instead of using a `comment_id` column (see more here - https://guides.rubyonrails.org/association_basics.html#polymorphic-associations)
  - Having a table for a user's news feed is a really interesting and clever approach, but I do have some questions about how you mean this to work: what does a record in this table represent? A post being on a user's news feed? If so, what user interactions would create new records in this table?

### Suggestions / Thoughts:
  - `friends`: 
    - I'd recommend a uniqueness constraint on the combination of `user_id` and `friend_id` (in both directions). Ie, if `{user_id: 1, friend_id: 4}` is already in the table, you shouldn't be able to add `{user_id: 1, friend_id: 4}` again, nor `{user_id: 4, friend_id: 1}`, as this represents a duplicate friendship 
    - If you choose to implement friend requests, you'd need to include that in your database. I think that could be done several ways (a separate requests table or another column in your friends table)

**Comment by tasnim-s** [comment]
1. Fields added to user table to fully populate user profile page. Null false for only the fields required during sign up.
2. Likes will be added with polymorphic association to posts and comments.
3. Newsfeed table will be removed and newsfeed content will be fetched using has many friends and has many posts associations
4. Friend table will have a dually linked connection by having two rows for every friend connection.
