### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by gorterd** [tasnim-s/HoloCron#3]
### To Revise:
  - [x] The users slice of state will need more data (anything that would be displayed on user profile: birthday, location, bio, etc)
  - [x] You'll also need to include properties for the image filenames / urls associated with users (cover photo and profile picture), as well as posts
  - [x] I'd recommend including created_at and/or update_at data with your comments and posts (it's both used in rendering, and can help for sorting)
  - [x] I'd recommend against including a newsFeed slice of state: a newsfeed isn't so much a distinct entity, in my mind, as it is a combination of certain posts from a user's friends.
    - If you meant the table in the backend to be a joins table (linking one post to one user), and you wanted to include a corresponding slice of state, I'd replicate that structure here (each newsFeed object having one userId and one postId)
    - However, I think it might be easier to just hit a special backend route / controller action to fetch a user's newsfeed posts when you navigate to that page, and then just replace the entire posts slice of state with those posts. Then, when a user navigates on their newsfeed, their newsfeed is just their posts slice of state.
### Suggestions / Thoughts:
  - If the current user has id 5, and they are friends with user 9, that friendship could be stored in the database, I assume, as either { user_id: 5, friend_id: 9 } or { user_id: 9, friend_id: 5 }. So if you're using the friends slice of state to grab all the users who are friends with the current user, your mSTP / selector might be a bit complex. One alternative would be to do that work in the backend, and include an array of friend_ids for user objects
  - Choosing to do friend requests would also require some additions here
  - Nice error messages!

**Comment by tasnim-s** [comment]
1. Active storage and aws will be used for file and image management(look at aws guide)

2. Jbuilder views will send back on creation of each post and comment the created at and updated at values

3. Newsfeed table and slice of state will be removed, associations will be used to populate the feed. Replace entire post slice with newly fetched posts
