### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by gorterd** [tasnim-s/HoloCron#4]
### To Revise:
  - [ ] No need to nest the friends#destroy route (presumably, the `:id` wildcard is pointing to the id of a particular row in the `friends` table, which represents a friendship between 2 users. Unfriending involves destroying one of those rows; you only need to have that row's id to find and delete it)
    - Will `api/users/:id/friends` fetch the users that are friends with one particular user? If so, you might consider having this be a custom route that hits the users controller
  - [x] You'll need a route for editing a user profile
### Suggestions / Thoughts:
  - You might consider including comments with the post `GET` requests, rather than having a dedicated route (in general, you don't want any 1 component to make more than 1 request to fetch the data it needs). Likewise, a comments#show route might not be necessary.
  - [ ] `Likes`: you'll need to have routes to like and unlike things, and include like data with some `GET` requests, once you get to the `Likes` MVP
  - Choosing to do friend requests would also require some additions here

**Comment by tasnim-s** [comment]
1. Edit profile route added to users

2. Comments and posts will be fetched with includes

3. Friends destroy will now look for two rows to delete on table
