### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by gorterd** [tasnim-s/HoloCron#6]
Awesome work, Tasnim! Honestly, I don't have much feedback; everything is on point: styling, functionality, even the custom logo; truly excellent work! The old bit of feedback I have relates to the error messages:

- [x] I'd style the error messages slightly more (maybe put them in a nicely styled box or something like that; just a bit inconsistent with the rest of the very polished styling )
- [x] I see the following when signing up. I'd make sure the sign-up error messages don't show up behind the modal.  ![Imgur](https://i.imgur.com/KhVYqR4.png)

**Comment by tasnim-s** [comment]
1. Error messages styled to appear underneath their respective input fields for more clean look.
2. Sign up error messages no longer show up behind the modal.

**Comment by gorterd** [comment]
Nice work!
